
import { GoogleGenAI } from "@google/genai";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
};

export const generateMockup = async (logoBase64: string, productPrompt: string): Promise<string> => {
  const ai = getAIClient();
  
  // Clean base64 string
  const base64Data = logoBase64.split(',')[1];
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: base64Data,
          },
        },
        {
          text: `Create a professional, high-end studio product photograph of ${productPrompt}. 
          Place the provided logo prominently and realistically on the product. 
          Use cinematic lighting and a clean, neutral background.
          The logo should look like it is physically printed on the material.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error('No image was generated by the AI.');
};

export const editMockup = async (imageBase64: string, editPrompt: string): Promise<string> => {
  const ai = getAIClient();
  
  const base64Data = imageBase64.split(',')[1];
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: base64Data,
          },
        },
        {
          text: `Modify this image based on the following instruction: "${editPrompt}". 
          Maintain the overall composition and the integrity of the product and logo, but apply the requested changes accurately.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error('Could not edit the image.');
};
